using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Practices.Unity;
using URP.DataAccess.Scaffolding;
using URP.Domain.Entities;

namespace URP.UI.ConsoleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            IUnityContainer container = UnityBootstrapper.Initialise();

            // Retrieve the unit of work class.
            var unitOfWork = container.Resolve<IUnitOfWork>();

            // Retrieve a repository from the IoC continer.
            var countryRepository = container.Resolve<IRepository<Country>>();
            
            int countryCount = countryRepository.Count();
            Console.WriteLine("Repository country count is: {0}", countryCount);
            
            Console.WriteLine("Adding the United Kingdom to the repository, but with a spelling mistake.");
            var country = new Country
                {   
                    Code = "GBP",
                    Name = "United Kingdon",
                    TelephoneCode = "+44"

                    // Don't populate the [CountryId]. It's the entities primary key and will be automatically 
                    // generated by the repository. 
                };

            countryRepository.Add(country);
            unitOfWork.Commit(); // Always commit after adding or updating an entity.

            countryCount = countryRepository.Count();
            Console.WriteLine("Repository country count is: {0}", countryCount);

            List<Country> countries = countryRepository.GetAll().ToList();
            foreach (var c in countries)
            {
                Console.Write("{0} exists in the database with an Id of [{1}] a Code of [{2}] and a telephone code of [{3}]",
                              c.Name,
                              c.CountryId,
                              c.Code,
                              c.TelephoneCode);
            }

            Console.WriteLine("Let's correct the spelling mistake.");
            country.Name = "United Kingdom"; 
            countryRepository.Update(country);
            unitOfWork.Commit();

            // Use a fresh object to prove that the updates have been committed to the repository.
            Country updatedCountry = countryRepository.GetById(country.CountryId);
            Console.WriteLine("{0} exists in the database with an Id of [{1}] a Code of [{2}] and a telephone code of [{3}]",
                          updatedCountry.Name,
                          updatedCountry.CountryId,
                          updatedCountry.Code,
                          updatedCountry.TelephoneCode);

            Console.WriteLine("Now delete the country from the repository.");
            Country countryToDelete = countryRepository.GetAll().FirstOrDefault();
            countryRepository.Delete(countryToDelete);
            unitOfWork.Commit();

            countryCount = countryRepository.Count();
            Console.WriteLine("Repository country count is: {0}", countryCount);

            Console.WriteLine("Press any key to continue...");
            Console.ReadLine();
        }
    }
}
